---
version: '2'
services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  kafka-1:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - zookeeper-1

    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  gateway:
    build:
      dockerfile: Dockerfile
      context: ./gateway
    depends_on:
      - kafka-1
    volumes:
      - /app/node_modules
      - ./gateway:/app
    ports:
      - 4000:4000

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - kafka-1
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - 3000:3000